# File: .github/workflows/template-sync.yml
# https://github.com/marketplace/actions/actions-template-sync

on:
  # cronjob trigger
  schedule:
  - cron:  "0 0 1 * *"

  # manual trigger
  workflow_dispatch:
name: Sync from Repo Template
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token to read from source repo # see: https://github.com/tibdex/github-app-token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - name: actions-template-sync
        id: actions_template_sync
        uses: AndreasAugustin/actions-template-sync@v0.8.0
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          source_repo_path: ScoopInstaller/BucketTemplate
          upstream_branch: master
          # pr_labels: <label1>,<label2>[,...] # optional, no default
      - name: "[debug] dump steps"
        run: echo '${{ toJSON(steps) }}'
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "<username>/<bucketname>"
          replace: "ppyv/scoop-jp-fonts"
          include: bin/auto-pr.ps1
          regex: false
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          branch: ${{ github.head_ref }}
